### ISSUE TITLE
117HD displays skybox only - Arch Linux

### ISSUE THREAD

**Issue by purojekuto** [117HD/RLHD#202] opened 2023-05-15 11:41 UTC
Much like the error below about OpenSUSE, I am only getting a skybox texture upon enabling 117HD plugin on Runelite.
![image](https://github.com/117HD/RLHD/assets/22593119/1885625a-21d1-4c47-97c8-27b958109fd3)

My system is up to date. I see someone mentioned the mesa drivers, here is my versions along with uname & kernel information.

extra/mesa 23.0.3-1 (14.7 MiB 85.3 MiB) (Installed)

Linux Arch 6.3.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000 x86_64 GNU/Linux

If you require any specifics let me know.

**Comment by aHooder** [comment] 2023-05-15 23:51
Can you try it with `mesa-git` from the AUR?

**Comment by aHooder** [comment] 2023-05-16 05:39
Duplicate of #195. See the latest comment there for more info.

**Closed by aHooder** 2023-05-16 05:39 UTC
