### ISSUE TITLE
Mesa 23.0.3 only renders the sky

### ISSUE THREAD

**Issue by gatiba** [117HD/RLHD#195] opened 2023-05-08 14:13 UTC
Hi,
on Linux using the RuneLite.AppImage executable and enabling 117 HD, all i see is a one color screen. If i disable the plugin, all is correctly rendered. 

I attach a screenshot, and thanks in advance.

![Screenshot_20230508_161206](https://user-images.githubusercontent.com/18282664/236846992-d77bc8a3-72bf-49b4-8beb-112b03891a5d.png)

**Comment by aHooder** [comment] 2023-05-08 14:14
I believe this is a Mesa driver bug. Can you try downgrading it, or possibly building the latest version?

**Comment by gatiba** [comment] 2023-05-08 14:38
Hi and thanks for your help, i'm using the latest available version on Tumbleweed (23.0.3-1599.350).
Unfortunately I don't have lower versions to install, looking at the repositories. :(

Maybe I just have to wait for the possible bug to be fixed...

**Comment by gatiba** [comment] 2023-05-15 13:33
Thanks for your feedback Purojekuto, my Mesa version on Tumbleweed is: 23.0.3-1699.350

I'm still experiencing the same problem, waiting for the bug to be fixed on a future update...

**Comment by aHooder** [comment] 2023-05-16 05:38
I did a little bit of digging on this, and was able to reproduce it locally. It looks like [this Mesa commit fixes it](https://gitlab.freedesktop.org/mesa/mesa/-/commit/3c9aa3e20136b65d794c36ebc5cb1311d1478f4b), so it will be fixed in Mesa 23.1.

**Comment by purojekuto** [comment] 2023-05-29 13:25
Hey, I can confirm the bug was fixed in the 23.1.1-1 release of mesa.

**Comment by aHooder** [comment] 2023-05-29 20:06
> Hey, I can confirm the bug was fixed in the 23.1.1-1 release of mesa.

Thanks, I'm closing this then :+1:

**Closed by aHooder** 2023-05-29 20:06 UTC
Labels: bug
