### ISSUE TITLE
Draynor bank entrance no good

### ISSUE THREAD

**Issue by j-meds** [117HD/RLHD#22] opened 2022-08-07 20:56 UTC
![image](https://user-images.githubusercontent.com/12689117/183310682-27edeaf7-c1b6-499d-95cf-ac2c368c7c02.png)

**Comment by xxEzri** [comment] 2022-08-07 21:08
@Sirfancybacon and i both found this independently in the last month or so also (:

To fix it with the current tools we need to know the underlay ID of the tiles which are already there, but we don't have any way of measuring what it is and can't test it without restarting runelite so it's really slow. Will probably update the underlay/overlay system or measurement tools so that it can be done more easily because this is an issue that comes up often.

**Comment by aHooder** [comment] 2022-08-07 21:12
> To fix it with the current tools we need to know the underlay ID of the tiles which are already there...

I'll try to get this tool fixed now

**Comment by aHooder** [comment] 2022-08-07 22:12
It seems like the issue that's making these tiles impossible to override is rooted pretty deeply. I don't know if I could fix it without breaking other stuff in unexpected ways. Maybe a solution would be to add yet another way to override tiles, that doesn't have this restriction?

**Comment by xxEzri** [comment] 2022-08-07 23:12
Yeah that sounds great

**Comment by SirFancyBacon** [comment] 2022-10-06 12:48
> It seems like the issue that's making these tiles impossible to override is rooted pretty deeply. I don't know if I could fix it without breaking other stuff in unexpected ways. Maybe a solution would be to add yet another way to override tiles, that doesn't have this restriction?

@aHooder 
With the changes i pulled in yesterday; Did this get resolved? Haven't tried since August and the issue is the same i talked about yesterday with the watch tower; texture shows up as "NONE" with a value of 1 which last i knew could not be replaced.

**Comment by aHooder** [comment] 2022-10-06 16:23
Yes, this is now possible to fix. The issue previously was that you couldn't apply overrides to tiles with both the overlay and underlay IDs being zero. Now it's possible to override purely based on world coordinates.

**Comment by SirFancyBacon** [comment] 2022-10-06 19:01
Hell yeah,
I'll look at fixing these if not tonight than tomorrow night

**Comment by SirFancyBacon** [comment] 2022-10-07 03:47
fixed by #80 when merged
![image](https://user-images.githubusercontent.com/11658143/194463830-1471f4cb-4c4a-4af5-9cfd-eaa386fe9c7c.png)

**Closed** 2022-10-08 13:26 UTC
