### ISSUE TITLE
Waterfall textures at ape atoll agility course.

### ISSUE THREAD

**Issue by Trottero** [117HD/RLHD#123] opened 2022-11-15 22:16 UTC
**Expected behavior**
Textures should be similar to those in the static bodies of water

**Screenshots**
![image](https://user-images.githubusercontent.com/15839811/202036364-464f7198-f89b-4b15-ab91-412b8abc5b37.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.9.3
 - Launcher version:  2.3.0

Just looks like a missing texture - Might go take a look at past issues and see how they are fixed to see if I can contribute myself.

**Comment by SirFancyBacon** [comment] 2022-11-16 02:19
Based on #114 these may have a similar root cause.

**Comment by Trottero** [comment] 2022-11-16 12:52
The texture for the priff waterfall looks good to me though, this one doesn't even have the water properly shaded.

**Comment by SirFancyBacon** [comment] 2022-11-16 14:09
Ohh so it is, Priff has an upsidedown UV.

I see that now

**Comment by SirFancyBacon** [comment] 2022-12-27 20:08
This issue also affects waterfalls on Lunar Island:
![image](https://user-images.githubusercontent.com/11658143/209717342-c027c5b3-e92c-468d-9a73-7b480362a192.png)

**Comment by SirFancyBacon** [comment] 2023-03-01 02:22
So i am wracking my brain over this water issue on waterfalls, Ape Atoll, Lunar Island, Waterfall quest area, and Motherloade Mine all only have one thing in common that i can think of. Animated textures; does the new water shaders added in november not handle those?

**Comment by aHooder** [comment] 2023-09-06 03:49
Ideally we'd have some new way to render water for waterfalls, but this is partially fixed by https://github.com/117HD/RLHD/commit/2713512d70ea294994afa82f6c48045f97d49066

![image](https://github.com/117HD/RLHD/assets/831317/472758b3-9968-45b9-91ea-2ab77e737175)
![image](https://github.com/117HD/RLHD/assets/831317/d1f89a66-4e54-4251-8c8f-41befc43ba23)

**Closed by aHooder** 2023-09-06 03:49 UTC
