### ISSUE TITLE
ROG ally RL  117 plugin crashes entire system

### ISSUE THREAD

**Issue by sumaznstyle** [117HD/RLHD#226] opened 2023-08-06 14:54 UTC
I load RL from jagex launcher and I can login but once i click play the entire system crash. I have provided the system even viewer logs along with RL logs as well 

Event viewer logs

Faulting application name: RuneLite.exe, version: 0.0.0.0, time stamp: 0x64bc8618
Faulting module name: atio6axx.dll, version: 31.0.14058.4001, time stamp: 0x648a0e03
Exception code: 0xc0000005
Fault offset: 0x0000000000c7304f
Faulting process id: 0x0x4690
Faulting application start time: 0x0x1D9C873B299850B
Faulting application path: C:\Users\sumaz\AppData\Local\RuneLite\RuneLite.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0392778.inf_amd64_829db4124e6a1944\B392868\atio6axx.dll
Report Id: fa1d175b-097f-471c-a8f5-6ca2b0325879
Faulting package full name: 
Faulting package-relative application ID: 

Faulting application name: RuneLite.exe, version: 0.0.0.0, time stamp: 0x64bc8618
Faulting module name: atio6axx.dll, version: 31.0.14058.4001, time stamp: 0x648a0e03
Exception code: 0xc0000005
Fault offset: 0x0000000000dc6209
Faulting process id: 0x0x51F8
Faulting application start time: 0x0x1D9C768ED483E0F
Faulting application path: C:\Users\sumaz\AppData\Local\RuneLite\RuneLite.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0392778.inf_amd64_829db4124e6a1944\B392868\atio6axx.dll
Report Id: c1711d2e-9621-43fb-9880-c523f5a55e82
Faulting package full name: 
Faulting package-relative application ID: 

Client log

2023-08-06 09:38:44 CDT [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.10.9.3 (launcher version 2.6.7) starting up, args: none
2023-08-06 09:38:44 CDT [RuneLite] INFO  net.runelite.client.RuneLite - Java VM arguments: -XX:+DisableAttachMechanism -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll,GTIII-OSD64-GL.dll,GTIII-OSD64-VK.dll,GTIII-OSD64.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Dsun.java2d.d3d=true -Dsun.java2d.opengl=false -Drunelite.launcher.version=2.6.7 -XX:ErrorFile=C:\Users\sumaz\.runelite\logs\jvm_crash_pid_%p.log
2023-08-06 09:38:46 CDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2023-08-06 09:38:46 CDT [Preloader] WARN  net.runelite.client.rs.ClientLoader - Cached patch hash mismatches, regenerating patch
2023-08-06 09:38:47 CDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 5771582223.217
2023-08-06 09:38:47 CDT [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: false, active: false)
2023-08-06 09:38:47 CDT [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: true, active: true)
2023-08-06 09:38:47 CDT [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'New Profile' (sync: false, active: false)
2023-08-06 09:38:47 CDT [RuneLite] INFO  n.r.client.config.ConfigManager - Using profile: default
2023-08-06 09:38:47 CDT [RuneLite] INFO  n.r.client.config.ConfigManager - Loading remote configuration for profile 'default'
2023-08-06 09:38:47 CDT [RuneLite] INFO  n.r.client.config.ConfigManager - Loading remote configuration for profile '$rsprofile'
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "equipment-inspector" jar "OCPmlSVAWvO9tyS_dvla63Wh64EuzRHy6H23z580eVk"
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "instant-idle-notify" jar "GySvr4LSvLemXOfKkeSb-fdtqTqqbk1x2GyPm4bhGDg"
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "3d-weather" jar "yFfLfPQZrnBiijrzi_JJ6whhlNpMKRBbbZbv3S-CMC4"
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-data-tracker" jar "vW2tWC77i7UhzpcKQsZLw_7XMfbVyLKpe6t7EANbbGI"
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wilderness-multi-lines" jar "L2zqBhQFkAunXhNhclEGQ9yK6caTKCh9JlZjY5PV5yA"
2023-08-06 09:38:48 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "spirit-tree-menu" jar "FXTJefxeoNdiTbNRBnrsdkBNO3sZTb31skiTXNMWbCk"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" jar "13KqJ3UDKNjfho3wFlZ3_ZQCHFqXYI2MuVE-wGfEE-c"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "flipping-utilities" jar "7Bm6fCjj9PWD2RyxvSTvPue0bhmf6mKCe2kNpCe0Shs"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "discord-loot-logger" jar "7spV36nhrB_sWtfPYMpk75mijkzP5xxs_szfDVmJQ54"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "npc-id" jar "S8X_6Mo38LRMkeitNOkgLuFM_N0m3Q2Pnbir5kswMqE"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-helper" jar "GSuDmLn5ghAMKyHzW4s_j6nME-8uWtl0iCQOD49ReGY"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" jar "msCZvJVnIWEHm4Sx0BPTercDjj_19T_VUJ9eX-2u1pw"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "improved-tears-of-guthix-interface" jar "nHFJkI_nVeoBCkTG2jF7ZQ7Nf4maUklc4zfhKlLv4To"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tile-packs" jar "4V1XSJFa5QWOPdNslTOLjRRRJFkDBNATTwAb-ozdWh0"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" jar "7Qqbz_Xj0-uwKRiiuxxcSn_NLeceme2qjxp_SSI3APA"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "clue-steps" jar "JboW8_surNGIfohq8LlNuzYS4bX66xFj1oGsZzUEFLk"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tictac7x-charges" jar "7Rpg4NMDog1zEirnjwY2xBpCiFMxmjSGtUL0h7GgCFE"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-light-colors" jar "n2tiCTpsoQGDRSHrLGiEEiw2pjeZnrfWeZJNkx2qS5Y"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ess-pouch" jar "mLOzuds7LU-HlBH2_JJ5t-AVOwzaW7UW6YJVbiMlAzI"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "toa-mistake-tracker" jar "awJwB7xz3B5zQuTHDV0KPQK2OW4jrZVJvvP_26Zwx-4"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "spawnpredictor" jar "75lC6NdDq1C5GcQr9OZdh5-0X0s2CZ7e9OSdyV57ZNY"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-lookup" jar "O6GjWoIkTb4FWXYV9QNdiSCNvZur4qdWT7A_vn-WDkQ"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shortest-path" jar "cDjOByESJoVkWGKzBbXZKk1oaYDCH5xi_Nqzu3gwnoE"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "guardians-of-the-rift-helper" jar "e9Zs-meeed_z1v3dYRHkxrv5BmpevIeyOj2EGs3cur8"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "barrows-door-highlighter" jar "Nd8nNsEY4Yu7FLelH33Fz8QlfeItrKew4bGfa_VDgec"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "runewatch" jar "H7LLaBJE8Qutox0Fw6LqInyf_QhT-4FsTRvA-yix4DE"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "better-npc-highlight" jar "sCfjxVEG732bSr_42E5P46IEmpJa33kKbf8xX4ZSkEI"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" jar "npJg80Xmkxz7Bmh_arxIuQK0PvwbmIcQWz2m4sX_COM"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "one-tick-flick-metronome" jar "ZG1-dA9lV8sFw6M1LhrhrLTpXEnv6Z0RG5_VORq5sGk"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "gauntlet" jar "W9ZhMSCBrhjh5HTFNIy-IYunvzJmBaA9S_Ol_NBKyC0"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "virtual-level-ups" jar "BB3S7NNTDug7TSxGitL3nbhtKqdExKFlXhnHaGKCj5g"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ping-grapher" jar "VMHjJW0ND3GjQ_RA3NGfrNr_J2crkxyJo2MSy0qDx_c"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "party-panel" jar "q2zw_OBBov9p7onW2almSNlE5DvfGWLJTCyGugSUrdc"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bats-locator" jar "uW5VeF1pTl9uRT2vHNQNbXDMdg2qKG4LskBGbjP_vSc"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cannon-highlighter" jar "PieGekVN0-MDwf55HC8TqZSQJMqDJp52KFOqwsa8hm8"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-screenshot" jar "IZufKrYCuV5BTG_C_rdIaDKSK90enfbn4iNxVcrLRKo"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "monster-hp-percentage" jar "jpqdoWaWakrxrwxVznJNDEFTBkEVYrGC1uqmmN_xLe4"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "herblorerecipes" jar "PaPZShLruL0dSlnDmQGLlRYmfwKRrUwuKp4Nz8Q0c9M"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "c-engineer-completed" jar "xjmk8x0Y8hHqt2MrXWNA_agj1H43r-sVECIqLrnNzjM"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "slayer-assistant" jar "X1fRyDETNlJP47eNOIvek7Ilc71uQOWKj3BV_uHE_dM"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "maxhitplugin" jar "14jkcHZypP2mKkSc8v8TbgRBwtlhIqifJclO60kLQ5E"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "annoyance-mute" jar "zkT-_uzVp3hy8SPzn_QFFNmecA_7R_Q013JMDzZnrSo"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tictac7x-tithe" jar "iJ287BkkINpg4w8wnAJpo3AA3HbINoCHcA2Uo8sUnKI"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "radius-markers" jar "-7S8DyKvSca2pivPielry7EZ33JMX4opHEi1kTVzUD4"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "chompy-hunter" jar "IYn6VGDoPxbmtBD9HiGVXFuVvWFbFbGDQ3ztWLVnmmQ"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menu-swapper-extended" jar "R4YEVIndemMutZQj0-WcwejLhph9-vKD0htb3kGOXOU"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "kph-tracker" jar "cjFV_xq1vIponMwzjPvh9ppVIVQvHFn0sTNt-SaOZyo"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "last-seen-online" jar "6HAhmX0x1qOGneHyRQEFrxycc0l2r2ZxQ-EE8am2PQM"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" jar "E9b0n9ip13i_Y8M-zWOHh9jFwuEUOvU_T4cJSIIpSxo"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "hotkeyable-menu-swaps" jar "81hkDGWs-2tnOtk87IzK7kkybRJy-XUElJSDu7t2-es"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "life-saver" jar "qbMl5xUYz425lNSW8IhBEtPMGlA88Yj7rf8agvgfJTA"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "watson-clue-tracker" jar "uBR0N7GoLqs9NUAN140H9jpMcDmzkIlBQIXni6UdX00"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tombs-of-amascut" jar "MFMF4fQhv88gzoxENHv6LX4KL2YlQcAyp3e8JAQBM1s"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-tag-layouts" jar "kuKNWYL50y7_oATtIgF0r5d-Dn2gaYiZZg-Xz5lmv64"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "shooting-stars-tracking" jar "uz9DD_bKTbePm5vWAx7sesJ4s0RZTMALaAS9oPcGBxw"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "herbi-afk" jar "aW2Hqdh8L5zjb1vElNZDSpR2XfX71qx-dSG3Y6ppo_A"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tictac7x-motherlode" jar "EkEPabIIGI_jtoyJlRxJrSPtI4s3zUluH3LleAKOkCQ"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "large-logout" jar "c5YRn4q8tzBbd_NktZ6QrWGSwqGPlw9NVGUuaWA-tpw"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "thrall-helper" jar "rb0AMXePWmpChDq5j2OkSkp4aeFUKZddB_HJW-qA6EE"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "easy-empty" jar "O3b9VVAgd8r0zpDYY1tO78PrHNeBYoSXmy7x1GrK340"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" jar "PRuTQnVfF--NnhixqTdgXS4Y_6o9Ewz5KosMU0W5fes"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "damage-counter" jar "BKGtCU91lIltCgu1AvD_wd30Z5DlHTvuBJyTopeVV3Q"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fish-barrel" jar "JTqJcmHGGdjZLG_ki3fztNA8TWkUIF7dATHhKjdzxr8"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "visual-sounds" jar "whxyqF45ke2aKGsPlawwe_pqOtc1dI-zFzwdgjH0t18"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "weapon-charges-2" jar "ubq7q1oOoKqMZf4TnyWBRybFPa6uuavqbvYHTtr42n4"
2023-08-06 09:38:49 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" jar "wIT0k06dFuHa1hnrbzqtdZtTIgHQ8pCXeoBtKqsmI7k"
2023-08-06 09:38:50 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "looting-bag-value" jar "vCc0tV9FkrIYpcHRzAMhs4WdF7yznJ39IYNZFB009Rs"
2023-08-06 09:38:50 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "birdhouse-overlay" jar "M3gC-oEMVUsO35Ii0wCc7wDD--RucN968XmVmFoKaZs"
2023-08-06 09:38:50 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "deathindicator" jar "46uPc6TOUWnTO4QOoVjMQ1k5GIlldZUIIPdJ1F7rK5E"
2023-08-06 09:38:50 CDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "profit-tracker" jar "FxuO7Kqdt6nqy8JHuK_1-SMgKHbSVK1NxW6d7810aW4"
2023-08-06 09:38:50 CDT [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2023-08-06 09:38:51 CDT [AWT-EventQueue-0] INFO  c.instantnotify.InstantNotifyPlugin - Instant Idle Notify started!
2023-08-06 09:38:52 CDT [AWT-EventQueue-0] INFO  c.f.controller.RecipeHandler - Successfully loaded recipes
2023-08-06 09:38:52 CDT [Client] INFO  c.f.controller.DataHandler - Initiating load on startup
2023-08-06 09:38:52 CDT [Client] INFO  c.f.db.TradePersister - flipping directory already exists so it's not being created
2023-08-06 09:38:52 CDT [Client] INFO  c.f.controller.DataHandler - Fetching account wide data
2023-08-06 09:38:52 CDT [Client] INFO  c.f.controller.DataHandler - successfully loaded account wide data
2023-08-06 09:38:52 CDT [Client] INFO  c.f.db.TradePersister - not loading data from file: accountwide.json
2023-08-06 09:38:52 CDT [Client] INFO  c.f.db.TradePersister - loading data for Lazi Snorlax
2023-08-06 09:38:52 CDT [Client] INFO  c.f.controller.DataHandler - Finished loading and preparing all accounts
2023-08-06 09:38:52 CDT [Client] INFO  c.f.controller.FlippingPlugin - changing view to Accountwide
2023-08-06 09:38:52 CDT [Client] INFO  c.f.jobs.WikiDataFetcherJob - started wiki fetching job
2023-08-06 09:38:52 CDT [Client] INFO  c.f.jobs.SlotSenderJob - started slot sender job
2023-08-06 09:38:52 CDT [Client] INFO  c.f.controller.ApiAuthHandler - no jwt stored locally, not attempting to check existing jwt
2023-08-06 09:38:52 CDT [AWT-EventQueue-0] INFO  com.easyEmpty.EasyEmptyPlugin - Easy Empty  started!
2023-08-06 09:38:53 CDT [pool-8-thread-1] INFO  c.f.jobs.CacheUpdaterJob - starting cache updator job!
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create a profile while not logged in
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create a profile while not logged in
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create a profile while not logged in
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create a profile while not logged in
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create a profile while not logged in
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create profile without display name
2023-08-06 09:38:53 CDT [Client] WARN  n.r.client.config.ConfigManager - trying to create a profile while not logged in
2023-08-06 09:38:53 CDT [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 9112ms. Uptime: 10526ms
2023-08-06 09:38:53 CDT [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Reset client position. Client bounds: 557x1x1244x1391
2023-08-06 09:38:53 CDT [Client] INFO  rs117.hd.HdPlugin - Using device: AMD Radeon Graphics
2023-08-06 09:38:53 CDT [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 Compatibility Profile Context 22.40.58.04.230614
2023-08-06 09:38:53 CDT [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2023-08-06 09:38:53 CDT [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user lazisnorlax.
2023-08-06 09:39:07 CDT [Client] WARN  n.r.client.config.ConfigManager - multiple matching profiles, choosing RuneScapeProfile(displayName=Lazi Snorlax, type=STANDARD, accountHash=8598831622853272861, key=rsprofile.HaWQa80v), ignoring [RuneScapeProfile(displayName=Lazi Snorlax, type=STANDARD, accountHash=8598831622853272861, key=rsprofile.hb_bslYp)]
2023-08-06 09:39:08 CDT [Client] INFO  c.f.controller.FlippingPlugin - Lazi Snorlax has just logged in!
2023-08-06 09:39:08 CDT [Client] INFO  c.f.controller.FlippingPlugin - changing view to Lazi Snorlax
2023-08-06 09:39:08 CDT [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login

**Comment by Zeppperoni** [comment] 2023-11-08 17:54
Same exact issues

Describe the bug
OpenGL 4.3 crashes ROG ally when enabling the 117HD plugin. When launching the plug and entering the game the plugin crashes the drivers on the ROG Ally

To Reproduce
Steps to reproduce the behavior:

have a ROG ally or any other AMD z1 extreme device with the current drivers as of 10/25/23
launch runelite
enable the 117 HD plugin
Log into the game
crash
Expected behavior
Not to crash when launching the game

Environment (please complete the following information):

OS: Windows 11
RuneLite version: 1.10.14.3
Launcher version: 0.29.1.0
Additional context
a few other folks have reported this issue on Reddit but no posts were found in the bug area.
The GPU plugin has the same issue however, it allows you to disable 'compute shaders' which cause the issue, and when disabled the plugin works.

Is it possible to disable compute shaders in the 117HD plugin?

**Comment by aHooder** [comment] 2023-11-08 17:56
It's not possible without a lot of code changes. Ideally we would figure out why the compute shader is crashing in the first place, but that may be easier said than done.

**Comment by Zeppperoni** [comment] 2023-11-08 17:59
> It's not possible without a lot of code changes. Ideally we would figure out why the compute shader is crashing in the first place, but that may be easier said than done.

Is there anything I can provide to assist with this?

**Comment by aHooder** [comment] 2023-11-08 18:03
With this type of crash, the only way for us to get anywhere is typically to modify the shader to try to isolate the cause of the crash, which can be pretty laborious. Driver crash logs (if there are any) would really only be useful to an AMD developer, assuming you're using closed source drivers. If you feel like dabbling in some shader development though, feel free to join our Discord and I can help you get set up.

**Comment by aHooder** [comment] 2024-07-14 09:05
I believe this might've been fixed for a while now with AMD's latest drivers. Can you give it another go and report back?

**Comment by sumaznstyle** [comment] 2024-07-14 09:29
Will do

**Comment by aHooder** [comment] 2024-07-18 18:17
I'll close this issue for now, as I believe this has been fixed in recent drivers. Feel free to reopen if it still crashes :slightly_smiling_face:

**Closed by aHooder** 2024-07-18 18:17 UTC

**Comment by sumaznstyle** [comment] 2024-07-21 03:41
I confirm this is working now
